# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops_ci_process?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: KINGsoft+5688

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21921
server:
  port: 21921
